#!/usr/bin/env zsh

DEFAULT_DOTFILES="$HOME/.dotfiles"
DOTFILES="${DOTFILES:-$DEFAULT_DOTFILES}"

DEFAULT_STOW_FOLDERS="git,nvim,zsh"
STOW_FOLDERS="${STOW_FOLDERS:-$DEFAULT_STOW_FOLDERS}"

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	stow -D $folder
done
popd
