#!/usr/bin/env zsh
source .env

# Manually setup brew - it has stow
eval "$(/opt/homebrew/bin/brew shellenv)"

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	stow -D $folder
	stow $folder
done
popd
