# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="" # disable oh-my-zsh themes

HYPHEN_INSENSITIVE="true"
DISABLE_LS_COLORS="true" # exa provides colors
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
plugins=(
  git
  docker
  docker-compose
  terraform
  cargo
  yarn
  zsh-autosuggestions # https://github.com/zsh-users/zsh-autosuggestions
  zsh-syntax-highlighting # https://github.com/zsh-users/zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# pure prompt
# https://github.com/sindresorhus/pure
fpath+=$HOME/.config/zsh/pure
autoload -U promptinit; promptinit
zstyle :prompt:pure:git:stash show yes
prompt pure

# User Config
MANPATH="/usr/local/man:$MANPATH"
LANG=en_US.UTF-8
SSH_KEY_PATH="/Users/gustavo/.ssh/rsa_id"

export HISTFILE="$HOME/.config/zsh/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
setopt appendhistory

# hstr
alias hh=hstr
setopt histignorespace           # skip cmds w/ leading space from history
export HSTR_CONFIG=prompt-bottom,hicolor,raw-history-view,help-on-opposite-side,keywords-matching,blacklist
export HSTR_PROMPT="$ "
bindkey -s "\C-r" "\C-a hstr -- \C-j"     # bind hstr to Ctrl-r (for Vi mode check doc)

# pyenv
# do i really want this?
export PYENV_SHELL=zsh
source '/usr/local/Cellar/pyenv/1.2.26/libexec/../completions/pyenv.zsh'
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(pyenv "sh-$command" "$@")";;
  *)
    command pyenv "$command" "$@";;
  esac
}

# aliases
alias vim="nvim"
alias vi='nvim'
alias less="less --LINE-NUMBERS"
alias localscan="nmap -sn 192.168.1.0/24"
alias ls="exa --group-directories-first"
alias cleanup="find . -type f \( -name '.DS_Store' -o -name '.localized' \) -delete"
alias valid-yaml="ruby -ryaml -e 'p YAML.load(STDIN.read)' < "
alias p3-venv="python3 -m venv env"
